# Generated by Django 4.0.3 on 2023-01-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_salesrecord_automobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autovo',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
