# Generated by Django 4.0.3 on 2023-01-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_automobilevo_color_automobilevo_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='technicia_name',
            new_name='technician_name',
        ),
    ]
