# Generated by Django 4.0.3 on 2023-01-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_appointment_cancelled_appointment_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='VIN',
        ),
        migrations.AddField(
            model_name='appointment',
            name='autos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='service_rest.automobilevo'),
        ),
    ]
