# Generated by Django 4.0.3 on 2023-01-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_remove_appointment_vin_appointment_autos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='autos',
            new_name='vin',
        ),
    ]
