# Generated by Django 4.0.3 on 2023-01-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_alter_appointment_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='automobile',
            new_name='vin',
        ),
    ]
