# Generated by Django 4.0.3 on 2023-01-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0012_rename_automobile_appointment_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='year',
        ),
        migrations.AddField(
            model_name='appointment',
            name='automobile_vin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service', to='service_rest.automobilevo'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=100),
        ),
    ]
