# Generated by Django 4.0.3 on 2023-01-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0013_remove_appointment_cancelled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='automobile_vin',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='technician',
        ),
        migrations.AddField(
            model_name='appointment',
            name='technician_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='service_rest.technician'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
